create table resource
(
    id           bigint generated by default as identity
        primary key,
    created_date timestamp,
    updated_date timestamp,
    author       varchar(255),
    date         varchar(255),
    like_count   numeric(30),
    title        varchar(255),
    url          varchar(255),
    view_count   numeric(30),
    constraint idx_author_title_url
        unique (title, author, url)
);